# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .artifact_parameter_properties_py3 import ArtifactParameterProperties
    from .artifact_install_properties_py3 import ArtifactInstallProperties
    from .apply_artifacts_request_py3 import ApplyArtifactsRequest
    from .arm_template_info_py3 import ArmTemplateInfo
    from .artifact_py3 import Artifact
    from .artifact_deployment_status_properties_py3 import ArtifactDeploymentStatusProperties
    from .artifact_source_py3 import ArtifactSource
    from .cost_per_day_properties_py3 import CostPerDayProperties
    from .cost_py3 import Cost
    from .vm_cost_properties_py3 import VMCostProperties
    from .cost_insight_py3 import CostInsight
    from .windows_os_info_py3 import WindowsOsInfo
    from .linux_os_info_py3 import LinuxOsInfo
    from .custom_image_properties_from_vm_py3 import CustomImagePropertiesFromVm
    from .custom_image_properties_custom_py3 import CustomImagePropertiesCustom
    from .custom_image_py3 import CustomImage
    from .day_details_py3 import DayDetails
    from .evaluate_policies_properties_py3 import EvaluatePoliciesProperties
    from .evaluate_policies_request_py3 import EvaluatePoliciesRequest
    from .policy_violation_py3 import PolicyViolation
    from .policy_set_result_py3 import PolicySetResult
    from .evaluate_policies_response_py3 import EvaluatePoliciesResponse
    from .gallery_image_reference_py3 import GalleryImageReference
    from .lab_virtual_machine_py3 import LabVirtualMachine
    from .formula_properties_from_vm_py3 import FormulaPropertiesFromVm
    from .formula_py3 import Formula
    from .gallery_image_py3 import GalleryImage
    from .parameter_info_py3 import ParameterInfo
    from .generate_arm_template_request_py3 import GenerateArmTemplateRequest
    from .generate_upload_uri_parameter_py3 import GenerateUploadUriParameter
    from .generate_upload_uri_response_py3 import GenerateUploadUriResponse
    from .hour_details_py3 import HourDetails
    from .lab_py3 import Lab
    from .lab_vhd_py3 import LabVhd
    from .policy_py3 import Policy
    from .week_details_py3 import WeekDetails
    from .schedule_py3 import Schedule
    from .subnet_py3 import Subnet
    from .subnet_override_py3 import SubnetOverride
    from .subscription_notification_properties_py3 import SubscriptionNotificationProperties
    from .subscription_notification_py3 import SubscriptionNotification
    from .virtual_network_py3 import VirtualNetwork
except (SyntaxError, ImportError):
    from .artifact_parameter_properties import ArtifactParameterProperties
    from .artifact_install_properties import ArtifactInstallProperties
    from .apply_artifacts_request import ApplyArtifactsRequest
    from .arm_template_info import ArmTemplateInfo
    from .artifact import Artifact
    from .artifact_deployment_status_properties import ArtifactDeploymentStatusProperties
    from .artifact_source import ArtifactSource
    from .cost_per_day_properties import CostPerDayProperties
    from .cost import Cost
    from .vm_cost_properties import VMCostProperties
    from .cost_insight import CostInsight
    from .windows_os_info import WindowsOsInfo
    from .linux_os_info import LinuxOsInfo
    from .custom_image_properties_from_vm import CustomImagePropertiesFromVm
    from .custom_image_properties_custom import CustomImagePropertiesCustom
    from .custom_image import CustomImage
    from .day_details import DayDetails
    from .evaluate_policies_properties import EvaluatePoliciesProperties
    from .evaluate_policies_request import EvaluatePoliciesRequest
    from .policy_violation import PolicyViolation
    from .policy_set_result import PolicySetResult
    from .evaluate_policies_response import EvaluatePoliciesResponse
    from .gallery_image_reference import GalleryImageReference
    from .lab_virtual_machine import LabVirtualMachine
    from .formula_properties_from_vm import FormulaPropertiesFromVm
    from .formula import Formula
    from .gallery_image import GalleryImage
    from .parameter_info import ParameterInfo
    from .generate_arm_template_request import GenerateArmTemplateRequest
    from .generate_upload_uri_parameter import GenerateUploadUriParameter
    from .generate_upload_uri_response import GenerateUploadUriResponse
    from .hour_details import HourDetails
    from .lab import Lab
    from .lab_vhd import LabVhd
    from .policy import Policy
    from .week_details import WeekDetails
    from .schedule import Schedule
    from .subnet import Subnet
    from .subnet_override import SubnetOverride
    from .subscription_notification_properties import SubscriptionNotificationProperties
    from .subscription_notification import SubscriptionNotification
    from .virtual_network import VirtualNetwork
from .lab_paged import LabPaged
from .lab_vhd_paged import LabVhdPaged
from .artifact_source_paged import ArtifactSourcePaged
from .artifact_paged import ArtifactPaged
from .cost_insight_paged import CostInsightPaged
from .cost_paged import CostPaged
from .custom_image_paged import CustomImagePaged
from .formula_paged import FormulaPaged
from .gallery_image_paged import GalleryImagePaged
from .policy_paged import PolicyPaged
from .schedule_paged import SchedulePaged
from .lab_virtual_machine_paged import LabVirtualMachinePaged
from .virtual_network_paged import VirtualNetworkPaged
from .dev_test_labs_client_enums import (
    SourceControlType,
    EnableStatus,
    CostPropertyType,
    WindowsOsState,
    LinuxOsState,
    CustomImageOsType,
    LabStorageType,
    PolicyStatus,
    PolicyFactName,
    PolicyEvaluatorType,
    TaskType,
    UsagePermissionType,
    SubscriptionNotificationState,
)

__all__ = [
    'ArtifactParameterProperties',
    'ArtifactInstallProperties',
    'ApplyArtifactsRequest',
    'ArmTemplateInfo',
    'Artifact',
    'ArtifactDeploymentStatusProperties',
    'ArtifactSource',
    'CostPerDayProperties',
    'Cost',
    'VMCostProperties',
    'CostInsight',
    'WindowsOsInfo',
    'LinuxOsInfo',
    'CustomImagePropertiesFromVm',
    'CustomImagePropertiesCustom',
    'CustomImage',
    'DayDetails',
    'EvaluatePoliciesProperties',
    'EvaluatePoliciesRequest',
    'PolicyViolation',
    'PolicySetResult',
    'EvaluatePoliciesResponse',
    'GalleryImageReference',
    'LabVirtualMachine',
    'FormulaPropertiesFromVm',
    'Formula',
    'GalleryImage',
    'ParameterInfo',
    'GenerateArmTemplateRequest',
    'GenerateUploadUriParameter',
    'GenerateUploadUriResponse',
    'HourDetails',
    'Lab',
    'LabVhd',
    'Policy',
    'WeekDetails',
    'Schedule',
    'Subnet',
    'SubnetOverride',
    'SubscriptionNotificationProperties',
    'SubscriptionNotification',
    'VirtualNetwork',
    'LabPaged',
    'LabVhdPaged',
    'ArtifactSourcePaged',
    'ArtifactPaged',
    'CostInsightPaged',
    'CostPaged',
    'CustomImagePaged',
    'FormulaPaged',
    'GalleryImagePaged',
    'PolicyPaged',
    'SchedulePaged',
    'LabVirtualMachinePaged',
    'VirtualNetworkPaged',
    'SourceControlType',
    'EnableStatus',
    'CostPropertyType',
    'WindowsOsState',
    'LinuxOsState',
    'CustomImageOsType',
    'LabStorageType',
    'PolicyStatus',
    'PolicyFactName',
    'PolicyEvaluatorType',
    'TaskType',
    'UsagePermissionType',
    'SubscriptionNotificationState',
]
