# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CostInsight(Model):
    """CostInsight.

    :param currency_code:
    :type currency_code: str
    :param vm_costs:
    :type vm_costs: list[~azure.mgmt.devtestlabs.models.VMCostProperties]
    :param provisioning_state: The provisioning status of the resource.
    :type provisioning_state: str
    :param id: The identifier of the resource.
    :type id: str
    :param name: The name of the resource.
    :type name: str
    :param type: The type of the resource.
    :type type: str
    :param location: The location of the resource.
    :type location: str
    :param tags: The tags of the resource.
    :type tags: dict[str, str]
    """

    _attribute_map = {
        'currency_code': {'key': 'properties.currencyCode', 'type': 'str'},
        'vm_costs': {'key': 'properties.vmCosts', 'type': '[VMCostProperties]'},
        'provisioning_state': {'key': 'properties.provisioningState', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '{str}'},
    }

    def __init__(self, *, currency_code: str=None, vm_costs=None, provisioning_state: str=None, id: str=None, name: str=None, type: str=None, location: str=None, tags=None, **kwargs) -> None:
        super(CostInsight, self).__init__(**kwargs)
        self.currency_code = currency_code
        self.vm_costs = vm_costs
        self.provisioning_state = provisioning_state
        self.id = id
        self.name = name
        self.type = type
        self.location = location
        self.tags = tags
