# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SubscriptionNotification(Model):
    """SubscriptionNotification.

    :param registration_date:
    :type registration_date: str
    :param state: Possible values include: 'NotDefined', 'Registered',
     'Unregistered', 'Warned', 'Suspended', 'Deleted'
    :type state: str or
     ~azure.mgmt.devtestlabs.models.SubscriptionNotificationState
    :param properties:
    :type properties:
     ~azure.mgmt.devtestlabs.models.SubscriptionNotificationProperties
    """

    _attribute_map = {
        'registration_date': {'key': 'registrationDate', 'type': 'str'},
        'state': {'key': 'state', 'type': 'str'},
        'properties': {'key': 'properties', 'type': 'SubscriptionNotificationProperties'},
    }

    def __init__(self, **kwargs):
        super(SubscriptionNotification, self).__init__(**kwargs)
        self.registration_date = kwargs.get('registration_date', None)
        self.state = kwargs.get('state', None)
        self.properties = kwargs.get('properties', None)
