# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class VMCostProperties(Model):
    """VMCostProperties.

    :param name:
    :type name: str
    :param resource_group_name:
    :type resource_group_name: str
    :param cost:
    :type cost: float
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'resource_group_name': {'key': 'resourceGroupName', 'type': 'str'},
        'cost': {'key': 'cost', 'type': 'float'},
    }

    def __init__(self, *, name: str=None, resource_group_name: str=None, cost: float=None, **kwargs) -> None:
        super(VMCostProperties, self).__init__(**kwargs)
        self.name = name
        self.resource_group_name = resource_group_name
        self.cost = cost
