# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .virtual_ip_mapping_py3 import VirtualIPMapping
    from .address_response_py3 import AddressResponse
    from .virtual_network_profile_py3 import VirtualNetworkProfile
    from .worker_pool_py3 import WorkerPool
    from .stamp_capacity_py3 import StampCapacity
    from .network_access_control_entry_py3 import NetworkAccessControlEntry
    from .name_value_pair_py3 import NameValuePair
    from .app_service_environment_py3 import AppServiceEnvironment
    from .app_service_environment_resource_py3 import AppServiceEnvironmentResource
    from .app_service_environment_patch_resource_py3 import AppServiceEnvironmentPatchResource
    from .hosting_environment_diagnostics_py3 import HostingEnvironmentDiagnostics
    from .metric_availabilily_py3 import MetricAvailabilily
    from .metric_definition_py3 import MetricDefinition
    from .sku_capacity_py3 import SkuCapacity
    from .capability_py3 import Capability
    from .sku_description_py3 import SkuDescription
    from .sku_info_py3 import SkuInfo
    from .usage_py3 import Usage
    from .worker_pool_resource_py3 import WorkerPoolResource
    from .vnet_route_py3 import VnetRoute
    from .vnet_info_py3 import VnetInfo
    from .vnet_gateway_py3 import VnetGateway
    from .user_py3 import User
    from .snapshot_py3 import Snapshot
    from .resource_metric_availability_py3 import ResourceMetricAvailability
    from .resource_metric_definition_py3 import ResourceMetricDefinition
    from .push_settings_py3 import PushSettings
    from .identifier_py3 import Identifier
    from .hybrid_connection_key_py3 import HybridConnectionKey
    from .hybrid_connection_py3 import HybridConnection
    from .deleted_site_py3 import DeletedSite
    from .proxy_only_resource_py3 import ProxyOnlyResource
    from .managed_service_identity_py3 import ManagedServiceIdentity
    from .slot_swap_status_py3 import SlotSwapStatus
    from .cloning_info_py3 import CloningInfo
    from .hosting_environment_profile_py3 import HostingEnvironmentProfile
    from .ip_security_restriction_py3 import IpSecurityRestriction
    from .api_definition_info_py3 import ApiDefinitionInfo
    from .cors_settings_py3 import CorsSettings
    from .auto_heal_custom_action_py3 import AutoHealCustomAction
    from .auto_heal_actions_py3 import AutoHealActions
    from .slow_requests_based_trigger_py3 import SlowRequestsBasedTrigger
    from .status_codes_based_trigger_py3 import StatusCodesBasedTrigger
    from .requests_based_trigger_py3 import RequestsBasedTrigger
    from .auto_heal_triggers_py3 import AutoHealTriggers
    from .auto_heal_rules_py3 import AutoHealRules
    from .site_limits_py3 import SiteLimits
    from .ramp_up_rule_py3 import RampUpRule
    from .experiments_py3 import Experiments
    from .virtual_directory_py3 import VirtualDirectory
    from .virtual_application_py3 import VirtualApplication
    from .handler_mapping_py3 import HandlerMapping
    from .site_machine_key_py3 import SiteMachineKey
    from .conn_string_info_py3 import ConnStringInfo
    from .azure_storage_info_value_py3 import AzureStorageInfoValue
    from .site_config_py3 import SiteConfig
    from .host_name_ssl_state_py3 import HostNameSslState
    from .site_py3 import Site
    from .app_service_plan_py3 import AppServicePlan
    from .resource_py3 import Resource
    from .default_error_response_error_details_item_py3 import DefaultErrorResponseErrorDetailsItem
    from .default_error_response_error_py3 import DefaultErrorResponseError
    from .default_error_response_py3 import DefaultErrorResponse, DefaultErrorResponseException
    from .resource_metric_property_py3 import ResourceMetricProperty
    from .resource_metric_value_py3 import ResourceMetricValue
    from .resource_metric_name_py3 import ResourceMetricName
    from .resource_metric_py3 import ResourceMetric
    from .localizable_string_py3 import LocalizableString
    from .csm_usage_quota_py3 import CsmUsageQuota
    from .web_app_collection_py3 import WebAppCollection
    from .error_entity_py3 import ErrorEntity
    from .operation_py3 import Operation
    from .app_service_plan_patch_resource_py3 import AppServicePlanPatchResource
    from .hybrid_connection_limits_py3 import HybridConnectionLimits
    from .certificate_py3 import Certificate
    from .certificate_patch_resource_py3 import CertificatePatchResource
    from .csm_operation_display_py3 import CsmOperationDisplay
    from .dimension_py3 import Dimension
    from .metric_availability_py3 import MetricAvailability
    from .metric_specification_py3 import MetricSpecification
    from .log_specification_py3 import LogSpecification
    from .service_specification_py3 import ServiceSpecification
    from .csm_operation_description_properties_py3 import CsmOperationDescriptionProperties
    from .csm_operation_description_py3 import CsmOperationDescription
    from .name_identifier_py3 import NameIdentifier
    from .solution_py3 import Solution
    from .detector_abnormal_time_period_py3 import DetectorAbnormalTimePeriod
    from .abnormal_time_period_py3 import AbnormalTimePeriod
    from .detector_definition_py3 import DetectorDefinition
    from .diagnostic_metric_sample_py3 import DiagnosticMetricSample
    from .diagnostic_metric_set_py3 import DiagnosticMetricSet
    from .data_source_py3 import DataSource
    from .response_meta_data_py3 import ResponseMetaData
    from .analysis_data_py3 import AnalysisData
    from .analysis_definition_py3 import AnalysisDefinition
    from .data_table_response_column_py3 import DataTableResponseColumn
    from .data_table_response_object_py3 import DataTableResponseObject
    from .detector_info_py3 import DetectorInfo
    from .rendering_py3 import Rendering
    from .diagnostic_data_py3 import DiagnosticData
    from .detector_response_py3 import DetectorResponse
    from .diagnostic_analysis_py3 import DiagnosticAnalysis
    from .diagnostic_category_py3 import DiagnosticCategory
    from .diagnostic_detector_response_py3 import DiagnosticDetectorResponse
    from .stack_minor_version_py3 import StackMinorVersion
    from .stack_major_version_py3 import StackMajorVersion
    from .application_stack_py3 import ApplicationStack
    from .recommendation_py3 import Recommendation
    from .recommendation_rule_py3 import RecommendationRule
    from .resource_health_metadata_py3 import ResourceHealthMetadata
    from .billing_meter_py3 import BillingMeter
    from .csm_move_resource_envelope_py3 import CsmMoveResourceEnvelope
    from .geo_region_py3 import GeoRegion
    from .hosting_environment_deployment_info_py3 import HostingEnvironmentDeploymentInfo
    from .deployment_locations_py3 import DeploymentLocations
    from .global_csm_sku_description_py3 import GlobalCsmSkuDescription
    from .premier_add_on_offer_py3 import PremierAddOnOffer
    from .resource_name_availability_py3 import ResourceNameAvailability
    from .resource_name_availability_request_py3 import ResourceNameAvailabilityRequest
    from .sku_infos_py3 import SkuInfos
    from .source_control_py3 import SourceControl
    from .validate_request_py3 import ValidateRequest
    from .validate_response_error_py3 import ValidateResponseError
    from .validate_response_py3 import ValidateResponse
    from .vnet_parameters_py3 import VnetParameters
    from .vnet_validation_test_failure_py3 import VnetValidationTestFailure
    from .vnet_validation_failure_details_py3 import VnetValidationFailureDetails
    from .file_system_application_logs_config_py3 import FileSystemApplicationLogsConfig
    from .azure_table_storage_application_logs_config_py3 import AzureTableStorageApplicationLogsConfig
    from .azure_blob_storage_application_logs_config_py3 import AzureBlobStorageApplicationLogsConfig
    from .application_logs_config_py3 import ApplicationLogsConfig
    from .azure_blob_storage_http_logs_config_py3 import AzureBlobStorageHttpLogsConfig
    from .azure_storage_property_dictionary_resource_py3 import AzureStoragePropertyDictionaryResource
    from .database_backup_setting_py3 import DatabaseBackupSetting
    from .backup_item_py3 import BackupItem
    from .backup_schedule_py3 import BackupSchedule
    from .backup_request_py3 import BackupRequest
    from .conn_string_value_type_pair_py3 import ConnStringValueTypePair
    from .connection_string_dictionary_py3 import ConnectionStringDictionary
    from .continuous_web_job_py3 import ContinuousWebJob
    from .csm_publishing_profile_options_py3 import CsmPublishingProfileOptions
    from .csm_slot_entity_py3 import CsmSlotEntity
    from .custom_hostname_analysis_result_py3 import CustomHostnameAnalysisResult
    from .deleted_app_restore_request_py3 import DeletedAppRestoreRequest
    from .deployment_py3 import Deployment
    from .enabled_config_py3 import EnabledConfig
    from .file_system_http_logs_config_py3 import FileSystemHttpLogsConfig
    from .function_envelope_py3 import FunctionEnvelope
    from .function_secrets_py3 import FunctionSecrets
    from .host_name_binding_py3 import HostNameBinding
    from .http_logs_config_py3 import HttpLogsConfig
    from .ms_deploy_py3 import MSDeploy
    from .ms_deploy_log_entry_py3 import MSDeployLogEntry
    from .ms_deploy_log_py3 import MSDeployLog
    from .ms_deploy_status_py3 import MSDeployStatus
    from .migrate_my_sql_request_py3 import MigrateMySqlRequest
    from .migrate_my_sql_status_py3 import MigrateMySqlStatus
    from .relay_service_connection_entity_py3 import RelayServiceConnectionEntity
    from .network_features_py3 import NetworkFeatures
    from .network_trace_py3 import NetworkTrace
    from .perf_mon_sample_py3 import PerfMonSample
    from .perf_mon_set_py3 import PerfMonSet
    from .perf_mon_response_py3 import PerfMonResponse
    from .premier_add_on_py3 import PremierAddOn
    from .premier_add_on_patch_resource_py3 import PremierAddOnPatchResource
    from .private_access_subnet_py3 import PrivateAccessSubnet
    from .private_access_virtual_network_py3 import PrivateAccessVirtualNetwork
    from .private_access_py3 import PrivateAccess
    from .process_thread_info_py3 import ProcessThreadInfo
    from .process_module_info_py3 import ProcessModuleInfo
    from .process_info_py3 import ProcessInfo
    from .public_certificate_py3 import PublicCertificate
    from .restore_request_py3 import RestoreRequest
    from .site_auth_settings_py3 import SiteAuthSettings
    from .site_cloneability_criterion_py3 import SiteCloneabilityCriterion
    from .site_cloneability_py3 import SiteCloneability
    from .site_config_resource_py3 import SiteConfigResource
    from .site_configuration_snapshot_info_py3 import SiteConfigurationSnapshotInfo
    from .site_extension_info_py3 import SiteExtensionInfo
    from .site_instance_py3 import SiteInstance
    from .site_logs_config_py3 import SiteLogsConfig
    from .site_patch_resource_py3 import SitePatchResource
    from .site_php_error_log_flag_py3 import SitePhpErrorLogFlag
    from .site_source_control_py3 import SiteSourceControl
    from .slot_config_names_resource_py3 import SlotConfigNamesResource
    from .slot_difference_py3 import SlotDifference
    from .snapshot_recovery_source_py3 import SnapshotRecoverySource
    from .snapshot_restore_request_py3 import SnapshotRestoreRequest
    from .storage_migration_options_py3 import StorageMigrationOptions
    from .storage_migration_response_py3 import StorageMigrationResponse
    from .string_dictionary_py3 import StringDictionary
    from .swift_virtual_network_py3 import SwiftVirtualNetwork
    from .triggered_job_run_py3 import TriggeredJobRun
    from .triggered_job_history_py3 import TriggeredJobHistory
    from .triggered_web_job_py3 import TriggeredWebJob
    from .web_job_py3 import WebJob
except (SyntaxError, ImportError):
    from .virtual_ip_mapping import VirtualIPMapping
    from .address_response import AddressResponse
    from .virtual_network_profile import VirtualNetworkProfile
    from .worker_pool import WorkerPool
    from .stamp_capacity import StampCapacity
    from .network_access_control_entry import NetworkAccessControlEntry
    from .name_value_pair import NameValuePair
    from .app_service_environment import AppServiceEnvironment
    from .app_service_environment_resource import AppServiceEnvironmentResource
    from .app_service_environment_patch_resource import AppServiceEnvironmentPatchResource
    from .hosting_environment_diagnostics import HostingEnvironmentDiagnostics
    from .metric_availabilily import MetricAvailabilily
    from .metric_definition import MetricDefinition
    from .sku_capacity import SkuCapacity
    from .capability import Capability
    from .sku_description import SkuDescription
    from .sku_info import SkuInfo
    from .usage import Usage
    from .worker_pool_resource import WorkerPoolResource
    from .vnet_route import VnetRoute
    from .vnet_info import VnetInfo
    from .vnet_gateway import VnetGateway
    from .user import User
    from .snapshot import Snapshot
    from .resource_metric_availability import ResourceMetricAvailability
    from .resource_metric_definition import ResourceMetricDefinition
    from .push_settings import PushSettings
    from .identifier import Identifier
    from .hybrid_connection_key import HybridConnectionKey
    from .hybrid_connection import HybridConnection
    from .deleted_site import DeletedSite
    from .proxy_only_resource import ProxyOnlyResource
    from .managed_service_identity import ManagedServiceIdentity
    from .slot_swap_status import SlotSwapStatus
    from .cloning_info import CloningInfo
    from .hosting_environment_profile import HostingEnvironmentProfile
    from .ip_security_restriction import IpSecurityRestriction
    from .api_definition_info import ApiDefinitionInfo
    from .cors_settings import CorsSettings
    from .auto_heal_custom_action import AutoHealCustomAction
    from .auto_heal_actions import AutoHealActions
    from .slow_requests_based_trigger import SlowRequestsBasedTrigger
    from .status_codes_based_trigger import StatusCodesBasedTrigger
    from .requests_based_trigger import RequestsBasedTrigger
    from .auto_heal_triggers import AutoHealTriggers
    from .auto_heal_rules import AutoHealRules
    from .site_limits import SiteLimits
    from .ramp_up_rule import RampUpRule
    from .experiments import Experiments
    from .virtual_directory import VirtualDirectory
    from .virtual_application import VirtualApplication
    from .handler_mapping import HandlerMapping
    from .site_machine_key import SiteMachineKey
    from .conn_string_info import ConnStringInfo
    from .azure_storage_info_value import AzureStorageInfoValue
    from .site_config import SiteConfig
    from .host_name_ssl_state import HostNameSslState
    from .site import Site
    from .app_service_plan import AppServicePlan
    from .resource import Resource
    from .default_error_response_error_details_item import DefaultErrorResponseErrorDetailsItem
    from .default_error_response_error import DefaultErrorResponseError
    from .default_error_response import DefaultErrorResponse, DefaultErrorResponseException
    from .resource_metric_property import ResourceMetricProperty
    from .resource_metric_value import ResourceMetricValue
    from .resource_metric_name import ResourceMetricName
    from .resource_metric import ResourceMetric
    from .localizable_string import LocalizableString
    from .csm_usage_quota import CsmUsageQuota
    from .web_app_collection import WebAppCollection
    from .error_entity import ErrorEntity
    from .operation import Operation
    from .app_service_plan_patch_resource import AppServicePlanPatchResource
    from .hybrid_connection_limits import HybridConnectionLimits
    from .certificate import Certificate
    from .certificate_patch_resource import CertificatePatchResource
    from .csm_operation_display import CsmOperationDisplay
    from .dimension import Dimension
    from .metric_availability import MetricAvailability
    from .metric_specification import MetricSpecification
    from .log_specification import LogSpecification
    from .service_specification import ServiceSpecification
    from .csm_operation_description_properties import CsmOperationDescriptionProperties
    from .csm_operation_description import CsmOperationDescription
    from .name_identifier import NameIdentifier
    from .solution import Solution
    from .detector_abnormal_time_period import DetectorAbnormalTimePeriod
    from .abnormal_time_period import AbnormalTimePeriod
    from .detector_definition import DetectorDefinition
    from .diagnostic_metric_sample import DiagnosticMetricSample
    from .diagnostic_metric_set import DiagnosticMetricSet
    from .data_source import DataSource
    from .response_meta_data import ResponseMetaData
    from .analysis_data import AnalysisData
    from .analysis_definition import AnalysisDefinition
    from .data_table_response_column import DataTableResponseColumn
    from .data_table_response_object import DataTableResponseObject
    from .detector_info import DetectorInfo
    from .rendering import Rendering
    from .diagnostic_data import DiagnosticData
    from .detector_response import DetectorResponse
    from .diagnostic_analysis import DiagnosticAnalysis
    from .diagnostic_category import DiagnosticCategory
    from .diagnostic_detector_response import DiagnosticDetectorResponse
    from .stack_minor_version import StackMinorVersion
    from .stack_major_version import StackMajorVersion
    from .application_stack import ApplicationStack
    from .recommendation import Recommendation
    from .recommendation_rule import RecommendationRule
    from .resource_health_metadata import ResourceHealthMetadata
    from .billing_meter import BillingMeter
    from .csm_move_resource_envelope import CsmMoveResourceEnvelope
    from .geo_region import GeoRegion
    from .hosting_environment_deployment_info import HostingEnvironmentDeploymentInfo
    from .deployment_locations import DeploymentLocations
    from .global_csm_sku_description import GlobalCsmSkuDescription
    from .premier_add_on_offer import PremierAddOnOffer
    from .resource_name_availability import ResourceNameAvailability
    from .resource_name_availability_request import ResourceNameAvailabilityRequest
    from .sku_infos import SkuInfos
    from .source_control import SourceControl
    from .validate_request import ValidateRequest
    from .validate_response_error import ValidateResponseError
    from .validate_response import ValidateResponse
    from .vnet_parameters import VnetParameters
    from .vnet_validation_test_failure import VnetValidationTestFailure
    from .vnet_validation_failure_details import VnetValidationFailureDetails
    from .file_system_application_logs_config import FileSystemApplicationLogsConfig
    from .azure_table_storage_application_logs_config import AzureTableStorageApplicationLogsConfig
    from .azure_blob_storage_application_logs_config import AzureBlobStorageApplicationLogsConfig
    from .application_logs_config import ApplicationLogsConfig
    from .azure_blob_storage_http_logs_config import AzureBlobStorageHttpLogsConfig
    from .azure_storage_property_dictionary_resource import AzureStoragePropertyDictionaryResource
    from .database_backup_setting import DatabaseBackupSetting
    from .backup_item import BackupItem
    from .backup_schedule import BackupSchedule
    from .backup_request import BackupRequest
    from .conn_string_value_type_pair import ConnStringValueTypePair
    from .connection_string_dictionary import ConnectionStringDictionary
    from .continuous_web_job import ContinuousWebJob
    from .csm_publishing_profile_options import CsmPublishingProfileOptions
    from .csm_slot_entity import CsmSlotEntity
    from .custom_hostname_analysis_result import CustomHostnameAnalysisResult
    from .deleted_app_restore_request import DeletedAppRestoreRequest
    from .deployment import Deployment
    from .enabled_config import EnabledConfig
    from .file_system_http_logs_config import FileSystemHttpLogsConfig
    from .function_envelope import FunctionEnvelope
    from .function_secrets import FunctionSecrets
    from .host_name_binding import HostNameBinding
    from .http_logs_config import HttpLogsConfig
    from .ms_deploy import MSDeploy
    from .ms_deploy_log_entry import MSDeployLogEntry
    from .ms_deploy_log import MSDeployLog
    from .ms_deploy_status import MSDeployStatus
    from .migrate_my_sql_request import MigrateMySqlRequest
    from .migrate_my_sql_status import MigrateMySqlStatus
    from .relay_service_connection_entity import RelayServiceConnectionEntity
    from .network_features import NetworkFeatures
    from .network_trace import NetworkTrace
    from .perf_mon_sample import PerfMonSample
    from .perf_mon_set import PerfMonSet
    from .perf_mon_response import PerfMonResponse
    from .premier_add_on import PremierAddOn
    from .premier_add_on_patch_resource import PremierAddOnPatchResource
    from .private_access_subnet import PrivateAccessSubnet
    from .private_access_virtual_network import PrivateAccessVirtualNetwork
    from .private_access import PrivateAccess
    from .process_thread_info import ProcessThreadInfo
    from .process_module_info import ProcessModuleInfo
    from .process_info import ProcessInfo
    from .public_certificate import PublicCertificate
    from .restore_request import RestoreRequest
    from .site_auth_settings import SiteAuthSettings
    from .site_cloneability_criterion import SiteCloneabilityCriterion
    from .site_cloneability import SiteCloneability
    from .site_config_resource import SiteConfigResource
    from .site_configuration_snapshot_info import SiteConfigurationSnapshotInfo
    from .site_extension_info import SiteExtensionInfo
    from .site_instance import SiteInstance
    from .site_logs_config import SiteLogsConfig
    from .site_patch_resource import SitePatchResource
    from .site_php_error_log_flag import SitePhpErrorLogFlag
    from .site_source_control import SiteSourceControl
    from .slot_config_names_resource import SlotConfigNamesResource
    from .slot_difference import SlotDifference
    from .snapshot_recovery_source import SnapshotRecoverySource
    from .snapshot_restore_request import SnapshotRestoreRequest
    from .storage_migration_options import StorageMigrationOptions
    from .storage_migration_response import StorageMigrationResponse
    from .string_dictionary import StringDictionary
    from .swift_virtual_network import SwiftVirtualNetwork
    from .triggered_job_run import TriggeredJobRun
    from .triggered_job_history import TriggeredJobHistory
    from .triggered_web_job import TriggeredWebJob
    from .web_job import WebJob
from .app_service_environment_resource_paged import AppServiceEnvironmentResourcePaged
from .stamp_capacity_paged import StampCapacityPaged
from .resource_metric_paged import ResourceMetricPaged
from .worker_pool_resource_paged import WorkerPoolResourcePaged
from .resource_metric_definition_paged import ResourceMetricDefinitionPaged
from .sku_info_paged import SkuInfoPaged
from .usage_paged import UsagePaged
from .app_service_plan_paged import AppServicePlanPaged
from .site_paged import SitePaged
from .csm_usage_quota_paged import CsmUsageQuotaPaged
from .str_paged import StrPaged
from .hybrid_connection_paged import HybridConnectionPaged
from .certificate_paged import CertificatePaged
from .deleted_site_paged import DeletedSitePaged
from .detector_response_paged import DetectorResponsePaged
from .diagnostic_category_paged import DiagnosticCategoryPaged
from .analysis_definition_paged import AnalysisDefinitionPaged
from .detector_definition_paged import DetectorDefinitionPaged
from .application_stack_paged import ApplicationStackPaged
from .csm_operation_description_paged import CsmOperationDescriptionPaged
from .recommendation_paged import RecommendationPaged
from .resource_health_metadata_paged import ResourceHealthMetadataPaged
from .source_control_paged import SourceControlPaged
from .billing_meter_paged import BillingMeterPaged
from .geo_region_paged import GeoRegionPaged
from .identifier_paged import IdentifierPaged
from .premier_add_on_offer_paged import PremierAddOnOfferPaged
from .backup_item_paged import BackupItemPaged
from .site_config_resource_paged import SiteConfigResourcePaged
from .site_configuration_snapshot_info_paged import SiteConfigurationSnapshotInfoPaged
from .continuous_web_job_paged import ContinuousWebJobPaged
from .deployment_paged import DeploymentPaged
from .function_envelope_paged import FunctionEnvelopePaged
from .host_name_binding_paged import HostNameBindingPaged
from .site_instance_paged import SiteInstancePaged
from .process_info_paged import ProcessInfoPaged
from .process_module_info_paged import ProcessModuleInfoPaged
from .process_thread_info_paged import ProcessThreadInfoPaged
from .perf_mon_response_paged import PerfMonResponsePaged
from .public_certificate_paged import PublicCertificatePaged
from .site_extension_info_paged import SiteExtensionInfoPaged
from .slot_difference_paged import SlotDifferencePaged
from .snapshot_paged import SnapshotPaged
from .triggered_web_job_paged import TriggeredWebJobPaged
from .triggered_job_history_paged import TriggeredJobHistoryPaged
from .web_job_paged import WebJobPaged
from .web_site_management_client_enums import (
    ProvisioningState,
    HostingEnvironmentStatus,
    InternalLoadBalancingMode,
    ComputeModeOptions,
    WorkerSizeOptions,
    AccessControlEntryAction,
    RouteType,
    ManagedServiceIdentityType,
    IpFilterTag,
    AutoHealActionType,
    ConnectionStringType,
    AzureStorageType,
    AzureStorageState,
    ScmType,
    ManagedPipelineMode,
    SiteLoadBalancing,
    SupportedTlsVersions,
    FtpsState,
    SslState,
    HostType,
    UsageState,
    SiteAvailabilityState,
    StatusOptions,
    OperationStatus,
    KeyVaultSecretStatus,
    IssueType,
    SolutionType,
    RenderingType,
    ResourceScopeType,
    NotificationLevel,
    Channels,
    AppServicePlanRestrictions,
    InAvailabilityReasonType,
    CheckNameResourceTypes,
    ValidateResourceTypes,
    LogLevel,
    BackupItemStatus,
    DatabaseType,
    FrequencyUnit,
    ContinuousWebJobStatus,
    WebJobType,
    PublishingProfileFormat,
    DnsVerificationTestResult,
    AzureResourceType,
    CustomHostNameDnsRecordType,
    HostNameType,
    MSDeployLogEntryType,
    MSDeployProvisioningState,
    MySqlMigrationType,
    PublicCertificateLocation,
    BackupRestoreOperationType,
    UnauthenticatedClientAction,
    BuiltInAuthenticationProvider,
    CloneAbilityResult,
    SiteExtensionType,
    TriggeredWebJobStatus,
    SkuName,
)

__all__ = [
    'VirtualIPMapping',
    'AddressResponse',
    'VirtualNetworkProfile',
    'WorkerPool',
    'StampCapacity',
    'NetworkAccessControlEntry',
    'NameValuePair',
    'AppServiceEnvironment',
    'AppServiceEnvironmentResource',
    'AppServiceEnvironmentPatchResource',
    'HostingEnvironmentDiagnostics',
    'MetricAvailabilily',
    'MetricDefinition',
    'SkuCapacity',
    'Capability',
    'SkuDescription',
    'SkuInfo',
    'Usage',
    'WorkerPoolResource',
    'VnetRoute',
    'VnetInfo',
    'VnetGateway',
    'User',
    'Snapshot',
    'ResourceMetricAvailability',
    'ResourceMetricDefinition',
    'PushSettings',
    'Identifier',
    'HybridConnectionKey',
    'HybridConnection',
    'DeletedSite',
    'ProxyOnlyResource',
    'ManagedServiceIdentity',
    'SlotSwapStatus',
    'CloningInfo',
    'HostingEnvironmentProfile',
    'IpSecurityRestriction',
    'ApiDefinitionInfo',
    'CorsSettings',
    'AutoHealCustomAction',
    'AutoHealActions',
    'SlowRequestsBasedTrigger',
    'StatusCodesBasedTrigger',
    'RequestsBasedTrigger',
    'AutoHealTriggers',
    'AutoHealRules',
    'SiteLimits',
    'RampUpRule',
    'Experiments',
    'VirtualDirectory',
    'VirtualApplication',
    'HandlerMapping',
    'SiteMachineKey',
    'ConnStringInfo',
    'AzureStorageInfoValue',
    'SiteConfig',
    'HostNameSslState',
    'Site',
    'AppServicePlan',
    'Resource',
    'DefaultErrorResponseErrorDetailsItem',
    'DefaultErrorResponseError',
    'DefaultErrorResponse', 'DefaultErrorResponseException',
    'ResourceMetricProperty',
    'ResourceMetricValue',
    'ResourceMetricName',
    'ResourceMetric',
    'LocalizableString',
    'CsmUsageQuota',
    'WebAppCollection',
    'ErrorEntity',
    'Operation',
    'AppServicePlanPatchResource',
    'HybridConnectionLimits',
    'Certificate',
    'CertificatePatchResource',
    'CsmOperationDisplay',
    'Dimension',
    'MetricAvailability',
    'MetricSpecification',
    'LogSpecification',
    'ServiceSpecification',
    'CsmOperationDescriptionProperties',
    'CsmOperationDescription',
    'NameIdentifier',
    'Solution',
    'DetectorAbnormalTimePeriod',
    'AbnormalTimePeriod',
    'DetectorDefinition',
    'DiagnosticMetricSample',
    'DiagnosticMetricSet',
    'DataSource',
    'ResponseMetaData',
    'AnalysisData',
    'AnalysisDefinition',
    'DataTableResponseColumn',
    'DataTableResponseObject',
    'DetectorInfo',
    'Rendering',
    'DiagnosticData',
    'DetectorResponse',
    'DiagnosticAnalysis',
    'DiagnosticCategory',
    'DiagnosticDetectorResponse',
    'StackMinorVersion',
    'StackMajorVersion',
    'ApplicationStack',
    'Recommendation',
    'RecommendationRule',
    'ResourceHealthMetadata',
    'BillingMeter',
    'CsmMoveResourceEnvelope',
    'GeoRegion',
    'HostingEnvironmentDeploymentInfo',
    'DeploymentLocations',
    'GlobalCsmSkuDescription',
    'PremierAddOnOffer',
    'ResourceNameAvailability',
    'ResourceNameAvailabilityRequest',
    'SkuInfos',
    'SourceControl',
    'ValidateRequest',
    'ValidateResponseError',
    'ValidateResponse',
    'VnetParameters',
    'VnetValidationTestFailure',
    'VnetValidationFailureDetails',
    'FileSystemApplicationLogsConfig',
    'AzureTableStorageApplicationLogsConfig',
    'AzureBlobStorageApplicationLogsConfig',
    'ApplicationLogsConfig',
    'AzureBlobStorageHttpLogsConfig',
    'AzureStoragePropertyDictionaryResource',
    'DatabaseBackupSetting',
    'BackupItem',
    'BackupSchedule',
    'BackupRequest',
    'ConnStringValueTypePair',
    'ConnectionStringDictionary',
    'ContinuousWebJob',
    'CsmPublishingProfileOptions',
    'CsmSlotEntity',
    'CustomHostnameAnalysisResult',
    'DeletedAppRestoreRequest',
    'Deployment',
    'EnabledConfig',
    'FileSystemHttpLogsConfig',
    'FunctionEnvelope',
    'FunctionSecrets',
    'HostNameBinding',
    'HttpLogsConfig',
    'MSDeploy',
    'MSDeployLogEntry',
    'MSDeployLog',
    'MSDeployStatus',
    'MigrateMySqlRequest',
    'MigrateMySqlStatus',
    'RelayServiceConnectionEntity',
    'NetworkFeatures',
    'NetworkTrace',
    'PerfMonSample',
    'PerfMonSet',
    'PerfMonResponse',
    'PremierAddOn',
    'PremierAddOnPatchResource',
    'PrivateAccessSubnet',
    'PrivateAccessVirtualNetwork',
    'PrivateAccess',
    'ProcessThreadInfo',
    'ProcessModuleInfo',
    'ProcessInfo',
    'PublicCertificate',
    'RestoreRequest',
    'SiteAuthSettings',
    'SiteCloneabilityCriterion',
    'SiteCloneability',
    'SiteConfigResource',
    'SiteConfigurationSnapshotInfo',
    'SiteExtensionInfo',
    'SiteInstance',
    'SiteLogsConfig',
    'SitePatchResource',
    'SitePhpErrorLogFlag',
    'SiteSourceControl',
    'SlotConfigNamesResource',
    'SlotDifference',
    'SnapshotRecoverySource',
    'SnapshotRestoreRequest',
    'StorageMigrationOptions',
    'StorageMigrationResponse',
    'StringDictionary',
    'SwiftVirtualNetwork',
    'TriggeredJobRun',
    'TriggeredJobHistory',
    'TriggeredWebJob',
    'WebJob',
    'AppServiceEnvironmentResourcePaged',
    'StampCapacityPaged',
    'ResourceMetricPaged',
    'WorkerPoolResourcePaged',
    'ResourceMetricDefinitionPaged',
    'SkuInfoPaged',
    'UsagePaged',
    'AppServicePlanPaged',
    'SitePaged',
    'CsmUsageQuotaPaged',
    'StrPaged',
    'HybridConnectionPaged',
    'CertificatePaged',
    'DeletedSitePaged',
    'DetectorResponsePaged',
    'DiagnosticCategoryPaged',
    'AnalysisDefinitionPaged',
    'DetectorDefinitionPaged',
    'ApplicationStackPaged',
    'CsmOperationDescriptionPaged',
    'RecommendationPaged',
    'ResourceHealthMetadataPaged',
    'SourceControlPaged',
    'BillingMeterPaged',
    'GeoRegionPaged',
    'IdentifierPaged',
    'PremierAddOnOfferPaged',
    'BackupItemPaged',
    'SiteConfigResourcePaged',
    'SiteConfigurationSnapshotInfoPaged',
    'ContinuousWebJobPaged',
    'DeploymentPaged',
    'FunctionEnvelopePaged',
    'HostNameBindingPaged',
    'SiteInstancePaged',
    'ProcessInfoPaged',
    'ProcessModuleInfoPaged',
    'ProcessThreadInfoPaged',
    'PerfMonResponsePaged',
    'PublicCertificatePaged',
    'SiteExtensionInfoPaged',
    'SlotDifferencePaged',
    'SnapshotPaged',
    'TriggeredWebJobPaged',
    'TriggeredJobHistoryPaged',
    'WebJobPaged',
    'ProvisioningState',
    'HostingEnvironmentStatus',
    'InternalLoadBalancingMode',
    'ComputeModeOptions',
    'WorkerSizeOptions',
    'AccessControlEntryAction',
    'RouteType',
    'ManagedServiceIdentityType',
    'IpFilterTag',
    'AutoHealActionType',
    'ConnectionStringType',
    'AzureStorageType',
    'AzureStorageState',
    'ScmType',
    'ManagedPipelineMode',
    'SiteLoadBalancing',
    'SupportedTlsVersions',
    'FtpsState',
    'SslState',
    'HostType',
    'UsageState',
    'SiteAvailabilityState',
    'StatusOptions',
    'OperationStatus',
    'KeyVaultSecretStatus',
    'IssueType',
    'SolutionType',
    'RenderingType',
    'ResourceScopeType',
    'NotificationLevel',
    'Channels',
    'AppServicePlanRestrictions',
    'InAvailabilityReasonType',
    'CheckNameResourceTypes',
    'ValidateResourceTypes',
    'LogLevel',
    'BackupItemStatus',
    'DatabaseType',
    'FrequencyUnit',
    'ContinuousWebJobStatus',
    'WebJobType',
    'PublishingProfileFormat',
    'DnsVerificationTestResult',
    'AzureResourceType',
    'CustomHostNameDnsRecordType',
    'HostNameType',
    'MSDeployLogEntryType',
    'MSDeployProvisioningState',
    'MySqlMigrationType',
    'PublicCertificateLocation',
    'BackupRestoreOperationType',
    'UnauthenticatedClientAction',
    'BuiltInAuthenticationProvider',
    'CloneAbilityResult',
    'SiteExtensionType',
    'TriggeredWebJobStatus',
    'SkuName',
]
