# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .sku_py3 import Sku
    from .cognitive_services_account_create_parameters_py3 import CognitiveServicesAccountCreateParameters
    from .cognitive_services_account_update_parameters_py3 import CognitiveServicesAccountUpdateParameters
    from .cognitive_services_account_py3 import CognitiveServicesAccount
    from .cognitive_services_account_keys_py3 import CognitiveServicesAccountKeys
    from .regenerate_key_parameters_py3 import RegenerateKeyParameters
    from .cognitive_services_resource_and_sku_py3 import CognitiveServicesResourceAndSku
    from .cognitive_services_account_enumerate_skus_result_py3 import CognitiveServicesAccountEnumerateSkusResult
    from .error_body_py3 import ErrorBody
    from .error_py3 import Error, ErrorException
except (SyntaxError, ImportError):
    from .sku import Sku
    from .cognitive_services_account_create_parameters import CognitiveServicesAccountCreateParameters
    from .cognitive_services_account_update_parameters import CognitiveServicesAccountUpdateParameters
    from .cognitive_services_account import CognitiveServicesAccount
    from .cognitive_services_account_keys import CognitiveServicesAccountKeys
    from .regenerate_key_parameters import RegenerateKeyParameters
    from .cognitive_services_resource_and_sku import CognitiveServicesResourceAndSku
    from .cognitive_services_account_enumerate_skus_result import CognitiveServicesAccountEnumerateSkusResult
    from .error_body import ErrorBody
    from .error import Error, ErrorException
from .cognitive_services_account_paged import CognitiveServicesAccountPaged
from .cognitive_services_management_client_enums import (
    SkuName,
    SkuTier,
    Kind,
    ProvisioningState,
    KeyName,
)

__all__ = [
    'Sku',
    'CognitiveServicesAccountCreateParameters',
    'CognitiveServicesAccountUpdateParameters',
    'CognitiveServicesAccount',
    'CognitiveServicesAccountKeys',
    'RegenerateKeyParameters',
    'CognitiveServicesResourceAndSku',
    'CognitiveServicesAccountEnumerateSkusResult',
    'ErrorBody',
    'Error', 'ErrorException',
    'CognitiveServicesAccountPaged',
    'SkuName',
    'SkuTier',
    'Kind',
    'ProvisioningState',
    'KeyName',
]
