# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class ModuleProvisioningState(str, Enum):

    created = "Created"
    creating = "Creating"
    starting_import_module_runbook = "StartingImportModuleRunbook"
    running_import_module_runbook = "RunningImportModuleRunbook"
    content_retrieved = "ContentRetrieved"
    content_downloaded = "ContentDownloaded"
    content_validated = "ContentValidated"
    connection_type_imported = "ConnectionTypeImported"
    content_stored = "ContentStored"
    module_data_stored = "ModuleDataStored"
    activities_stored = "ActivitiesStored"
    module_import_runbook_complete = "ModuleImportRunbookComplete"
    succeeded = "Succeeded"
    failed = "Failed"
    cancelled = "Cancelled"
    updating = "Updating"


class JobStreamType(str, Enum):

    progress = "Progress"
    output = "Output"
    warning = "Warning"
    error = "Error"
    debug = "Debug"
    verbose = "Verbose"
    any = "Any"


class RunbookTypeEnum(str, Enum):

    script = "Script"
    graph = "Graph"
    power_shell_workflow = "PowerShellWorkflow"
    power_shell = "PowerShell"
    graph_power_shell_workflow = "GraphPowerShellWorkflow"
    graph_power_shell = "GraphPowerShell"


class RunbookState(str, Enum):

    new = "New"
    edit = "Edit"
    published = "Published"


class RunbookProvisioningState(str, Enum):

    succeeded = "Succeeded"


class HttpStatusCode(str, Enum):

    continue_enum = "Continue"
    switching_protocols = "SwitchingProtocols"
    ok = "OK"
    created = "Created"
    accepted = "Accepted"
    non_authoritative_information = "NonAuthoritativeInformation"
    no_content = "NoContent"
    reset_content = "ResetContent"
    partial_content = "PartialContent"
    multiple_choices = "MultipleChoices"
    ambiguous = "Ambiguous"
    moved_permanently = "MovedPermanently"
    moved = "Moved"
    found = "Found"
    redirect = "Redirect"
    see_other = "SeeOther"
    redirect_method = "RedirectMethod"
    not_modified = "NotModified"
    use_proxy = "UseProxy"
    unused = "Unused"
    temporary_redirect = "TemporaryRedirect"
    redirect_keep_verb = "RedirectKeepVerb"
    bad_request = "BadRequest"
    unauthorized = "Unauthorized"
    payment_required = "PaymentRequired"
    forbidden = "Forbidden"
    not_found = "NotFound"
    method_not_allowed = "MethodNotAllowed"
    not_acceptable = "NotAcceptable"
    proxy_authentication_required = "ProxyAuthenticationRequired"
    request_timeout = "RequestTimeout"
    conflict = "Conflict"
    gone = "Gone"
    length_required = "LengthRequired"
    precondition_failed = "PreconditionFailed"
    request_entity_too_large = "RequestEntityTooLarge"
    request_uri_too_long = "RequestUriTooLong"
    unsupported_media_type = "UnsupportedMediaType"
    requested_range_not_satisfiable = "RequestedRangeNotSatisfiable"
    expectation_failed = "ExpectationFailed"
    upgrade_required = "UpgradeRequired"
    internal_server_error = "InternalServerError"
    not_implemented = "NotImplemented"
    bad_gateway = "BadGateway"
    service_unavailable = "ServiceUnavailable"
    gateway_timeout = "GatewayTimeout"
    http_version_not_supported = "HttpVersionNotSupported"
