# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .max_size_capability_py3 import MaxSizeCapability
    from .performance_level_capability_py3 import PerformanceLevelCapability
    from .service_level_objective_capability_py3 import ServiceLevelObjectiveCapability
    from .edition_capability_py3 import EditionCapability
    from .elastic_pool_per_database_min_dtu_capability_py3 import ElasticPoolPerDatabaseMinDtuCapability
    from .elastic_pool_per_database_max_dtu_capability_py3 import ElasticPoolPerDatabaseMaxDtuCapability
    from .elastic_pool_dtu_capability_py3 import ElasticPoolDtuCapability
    from .elastic_pool_edition_capability_py3 import ElasticPoolEditionCapability
    from .server_version_capability_py3 import ServerVersionCapability
    from .location_capabilities_py3 import LocationCapabilities
    from .subscription_usage_py3 import SubscriptionUsage
    from .tracked_resource_py3 import TrackedResource
    from .resource_py3 import Resource
    from .proxy_resource_py3 import ProxyResource
except (SyntaxError, ImportError):
    from .max_size_capability import MaxSizeCapability
    from .performance_level_capability import PerformanceLevelCapability
    from .service_level_objective_capability import ServiceLevelObjectiveCapability
    from .edition_capability import EditionCapability
    from .elastic_pool_per_database_min_dtu_capability import ElasticPoolPerDatabaseMinDtuCapability
    from .elastic_pool_per_database_max_dtu_capability import ElasticPoolPerDatabaseMaxDtuCapability
    from .elastic_pool_dtu_capability import ElasticPoolDtuCapability
    from .elastic_pool_edition_capability import ElasticPoolEditionCapability
    from .server_version_capability import ServerVersionCapability
    from .location_capabilities import LocationCapabilities
    from .subscription_usage import SubscriptionUsage
    from .tracked_resource import TrackedResource
    from .resource import Resource
    from .proxy_resource import ProxyResource
from .subscription_usage_paged import SubscriptionUsagePaged
from .sql_management_client_enums import (
    MaxSizeUnits,
    CapabilityStatus,
    PerformanceLevelUnit,
)

__all__ = [
    'MaxSizeCapability',
    'PerformanceLevelCapability',
    'ServiceLevelObjectiveCapability',
    'EditionCapability',
    'ElasticPoolPerDatabaseMinDtuCapability',
    'ElasticPoolPerDatabaseMaxDtuCapability',
    'ElasticPoolDtuCapability',
    'ElasticPoolEditionCapability',
    'ServerVersionCapability',
    'LocationCapabilities',
    'SubscriptionUsage',
    'TrackedResource',
    'Resource',
    'ProxyResource',
    'SubscriptionUsagePaged',
    'MaxSizeUnits',
    'CapabilityStatus',
    'PerformanceLevelUnit',
]
